# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "github.com/gogo/protobuf/proto",
  "github.com/gogo/protobuf/jsonpb",
  "github.com/gogo/protobuf/protoc-gen-gogoslick",
  "github.com/gogo/protobuf/gogoproto",
]

[[constraint]]
  name = "istio.io/api"
  revision = "6ce328b48d94e90f3c8022e811b875453da05477"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "=0.5"
